### ISSUE TITLE
How to apply Diamond Proxy to Factory contract?

### ISSUE THREAD

**Issue by lucaslee129** [mudgen/diamond-2#13]
Hi, Mr. Mudgen. Thanks for your contribution to Web3 ecosystem.
Currently, I am working with Diamond Proxy contract.
At first, I built normal smart contract, but the requirement is arising to upgrade that. So I have to it to upgradeable contract and chose the Diamond Pattern. But my contract is factory contract. As you know, this contract deployed new contract in its logic.

Currently, I am studying Diamond Proxy while developing, but I dont know to do implement this.
Could you kindly provide me some support for this, please? 
I hope your kind answering.

P.S. I am a fresh to the Diamond Pattern, I hope more active conversation for this.
I am really appreciate if you contact me here.
Telegram: @lucas2me777
Skype: live:.cid.a250cf69d1c7dd37
Whatapp: +1 908 514 4288

**Comment by ItsNickBarry** [comment]
You can use a beacon pattern.  Here's an example: https://github.com/Premian-Labs/premia-contracts/blob/master/contracts/pool/PoolProxy.sol

The `PoolProxy` is a proxy that queries its implementation from a diamond (see `_getImplementation` function).  The diamond is used only for the purpose of providing this implementation information to the proxies.

I've been working on a standardized diamond beacon pattern in my Solidstate project, but it's not released yet: https://github.com/solidstate-network/solidstate-solidity/pull/233
