### ISSUE TITLE
How to init contract owner address?

### ISSUE THREAD

**Issue by cryptostar7** [mudgen/diamond-2#14]
Hi, How are you? I have some problems while using diamond-2 proxy contract.
I deployed the diamond contracts using deploying script on project.(I have no change any files on project).
Then when I tried to add new facet to diamond proxy, I received error message which is invalid contract owner.
So I called the owner function on ownershipFacet contract. The result was zero address.
How to fix this problem? Hope your kind reply. Thanks.

**Comment by ItsNickBarry** [comment]
Call the `owner` function on the diamond proxy contract, not on the facet contract.  You'll need to use the ABI from the facet along with the address from the diamond.

You can see that the owner is being set in the diamond constructor here: https://github.com/mudgen/diamond-2/blob/636b724613d0731418ba364a5d82aaad8a531025/contracts/Diamond.sol#L27

**Comment by lucaslee129** [comment]
Thanks for your kind answering.
But after deploying contract using deploying script on diamond-2 project, I tried to call diamondCut funtion of diamondCutFacet contract to add new facet using ethers.js. In this case, the error which is "LibDiamond: Must be contract owner" occurred. 
So I didnt add facet. 
Please let me know how to fix this problem and how to add facet after deploying contracts on diamond-2 project.
Thanks for your kindness and hope your kind reply.

**Comment by ItsNickBarry** [comment]
Make sure you're passing the right owner address to the diamond constructor, and then using that address to send your transactions.  If the problem persists, I suggest you post in the Diamonds Discord server (linked in Readme).

**Comment by lucaslee129** [comment]
Thanks. I used the deploying script without modification. And I checked deploying script implementation that.
Here is the code snippet on deploying script.

```
...
const accounts = await ethers.getSigners()
  const contractOwner = accounts[0]

  console.log("Contract Owner address>>>>", contractOwner.address);

  // deploy DiamondCutFacet
  const DiamondCutFacet = await ethers.getContractFactory('DiamondCutFacet')
  const diamondCutFacet = await DiamondCutFacet.deploy()
  await diamondCutFacet.deployed()
  console.log('DiamondCutFacet deployed:', diamondCutFacet.address)

  // deploy Diamond
  const Diamond = await ethers.getContractFactory('Diamond')
  const diamond = await Diamond.deploy(contractOwner.address, diamondCutFacet.address)
  await diamond.deployed()
  console.log('Diamond deployed:', diamond.address)
...
```

Here, I checked my address using console log.
Thanks again and hope your kind support.

**Comment by mudgen** [comment]
@lucaslee129 I suggest that you use the newer version of this implementation which is here: https://github.com/mudgen/diamond-2-hardhat
